const CONST = {
  "HTTP_STATUS_CODE": {
    "SUCCESS": 200,
    "CREATED": 201,
    "ACCEPTED": 202,
    "NO_CONTENT": 204,
    "BAD_REQUEST": 400,
    "UNAUTHORIZED": 401,
    "FORBIDDEN": 403,
    "NOT_FOUND": 404,
    "METHOD_NOT_ALLOWED": 405,
    "NOT_ACCEPTABLE": 406,
    "PRECONDITION_FAILED": 412,
    "INTERNAL_SERVER_ERROR": 500,
    "NOT_IMPLEMENTED": 501
  },

  PROFILE_STATUS: {
    GUEST: 'GUEST'
  }
}

module.exports = CONST;